spring:
  profiles: default

token:
  expiration_time:  86400000
  secret: Imstudyingspringcloudjwtissomuchfun

gateway:
  ip: 192.168.0.8

---

spring:
  profiles: dev

token:
  expiration_time:  86400000
  secret: '{cipher}AQBUQQ88RgkXKiTcGQwAYU2TPOXJCVhv2vdtspq31fOl+KRjqvWNhydEqMKP3VvHyrTFyYZ46Jjad/A9jtd20iIoDvsNvBIS7RgrO+IoKt2ivEln+uvAnV9QVEApsxmcXwTpjijO21yIr2rOSf7rsfa2J8b4mEvurVR+eQalcspkfmKb/fpyewxTLJcTjvbYystb+ZjPmur0g900arVIEOc+40Qx/1ykxhNGk93CdojLueKDGEKiOvhsWJl+8gihAiQI/ZlNJn45+U2dMPrcztC2ZK46nYpimGvQVZndClyIMZcgb1FSgmjfcPjwNDnfVCf9sjyV3+rpJfAi3QioiV46EngM1Lg4h6hoA0O75C/kv2hA3ASztTercUlRxCpNTQFZv3jlvUFGeyolMk97eel/hq3qBIY1/r7vIWx2498inmdw1mf+Usn7dwLbDgoQm7k='

gateway:
  ip: 192.168.0.8

---

spring:
  profiles: prod

token:
  expiration_time:  86400000
  secret: Imstudyingspringcloudjwtissomuchfun_Prod

gateway:
  ip: 192.168.0.8