url:
  order-service: '{cipher}AQA6K5E4ZGmsDWYkfvCABQjbsTo4UX5GkH45HF/jYZpjiRAXrawO3kRejHXaEax8ntkFeprKEdQr359eXbKUuh3lRkUeqUgPMuuGtSbsMqmnhs1U/a3MG1jD9Rmo2qgGe14+eAAFAM6e4df9vt65t/6FizjxDXdJqWF9RPfoLDoHOTJHznLmh1XMRX5skKcv4lhTOZSuBV0Q5claIPNJNHDkMuD5ny8rVFjnJYvOPONL33FRndPnso6SwEvHWNWNQuygSG+pc3SBSwOKi3/bvwEg5JaFm435kmZp2zdpUTR7K6Nej19Zl/Ibw8fM5IhQpqhi7hwD5SiELHgsDSIv1tx+6XONRq9XBBEHwBDqFtxAX9F3M46Awx8aFABvhZQzUctlL+1IAlhYukjv6UuzUYpzuAgLzrEmh2+Gv4cCREDWWA=='

---

spring:
  profiles: dev

token:
  expiration_time:  86400000
  secret: '{cipher}AQBUQQ88RgkXKiTcGQwAYU2TPOXJCVhv2vdtspq31fOl+KRjqvWNhydEqMKP3VvHyrTFyYZ46Jjad/A9jtd20iIoDvsNvBIS7RgrO+IoKt2ivEln+uvAnV9QVEApsxmcXwTpjijO21yIr2rOSf7rsfa2J8b4mEvurVR+eQalcspkfmKb/fpyewxTLJcTjvbYystb+ZjPmur0g900arVIEOc+40Qx/1ykxhNGk93CdojLueKDGEKiOvhsWJl+8gihAiQI/ZlNJn45+U2dMPrcztC2ZK46nYpimGvQVZndClyIMZcgb1FSgmjfcPjwNDnfVCf9sjyV3+rpJfAi3QioiV46EngM1Lg4h6hoA0O75C/kv2hA3ASztTercUlRxCpNTQFZv3jlvUFGeyolMk97eel/hq3qBIY1/r7vIWx2498inmdw1mf+Usn7dwLbDgoQm7k='

gateway:
  ip: 192.168.0.8

---

spring:
  profiles: prod

token:
  expiration_time:  86400000
  secret: '{ciper}AQAJMY7nGNYDSB6oZV7ZvE8y0I8TT9G49as5Lnin3y9JEXkQjT/6TyJxtz7Hu8mJN8evBYzSpcwTs6G1giaLlI7wKFKmPoOsnl7gdM/TdYfLrdui97FjnUrPfBQrqQT5a2n65bwGWmD1D1ZJSfzZ4wNpXP6qXloAv56T0YztC2KPs11yTndWNwgFrPCdg0kUhcnXS3zkNWd1m05Nf/4csGBLfYx1adB7Skyp6M1sxePmivpmmpjMimjeCowbJ8m0+qSs3GPTG9HTJbWCNGvOpFUQlrWdhDMPHQUSelxKuvaQD1yBoaN816pGq42X0F+qC7W7FJPY6NPQeDcS5GLSD3mlbZlfKXU7Nm5MyqjkBRqEspYjDC0Jwie82iCh70qFFniq/ErZh2LzmV2Sgq+OGv74zX3GScqWhLv8RziClncSZA=='

gateway:
  ip: 192.168.0.8