server:
  port: 0

spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  config: # spring config server import
    import: optional:configserver:http://localhost:8888
  cloud: # config server .yml 이름 지정
    config:
      name: ecommerce
      profile: dev

# Actuator 등록
management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
          - beans

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


simple:
  message: Simple E-commerce.

logging:
  level:
    springcloudstudy:
      usermicroservices: debug

# expridationTime = 60(초) * 60(분) * 24 * 10000 -> 하루 milliSec
# secret = 32글자 이상
#token:
#  expiration_time: 86400000
#  secret: Imstudyingspringcloudjwtissomuchfun