server:
  port: 8888

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  application:
    name: config-server
  cloud:
    config:
      server:
        git:
#          uri: file:///Users/yc/study/back/code/spring-cloud/git-local-config # local .yml 사용, git commit 상태
          uri: https://github.com/yeongchan1228/spring-cloud.git
#          private repository 시
#          username: ~~~~ # git
#          password: ~~~~ # git

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS